### ISSUE TITLE
With how many participants should we plan for the Julia workshop?

### ISSUE THREAD

**Issue by aaronpeikert** [MalikaIhle/OSC-Open-Research-Summer-School-2023#2]

**Comment by MalikaIhle** [comment]
I think you should plan for e.g. 25 because I could open up this workshop as an individual session that can be attended without applying for the summer school if there isn't enough people from the selected applicants that plan to attend it. They will express their preference in July during the application process. What do you think?

**Comment by aaronpeikert** [comment]
Given the self-paced nature and having 3 instructors, I think we might even manage a couple more. At least 30? Even 40 sounds reasonable to me.

**Comment by MalikaIhle** [comment]
ok! then I'll definitively open it for public registration!

**Comment by MalikaIhle** [comment]
Aaron - do you have a Zoom pro account ? just asking to see what my options are to organise the parallel workshops

**Comment by aaronpeikert** [comment]
> Aaron - do you have a Zoom pro account ? just asking to see what my options are to organise the parallel workshops

I will no longer have a Zoom account, no, but Maximilian or Moritz should have one from HU Berlin.
